name: NoisyCircuits_New_Branch
channels:
  - conda-forge
dependencies:
  - python=3.10.14
  - joblib
  - pip
  - matplotlib
  - pip:
    - pennylane
    - qiskit
    - qiskit-aer
    - qiskit-ibm-runtime
    - ray