name: NoisyCircuits
channels:
  - conda-forge
dependencies:
  - python=3.10.14
  - joblib
  - pip
  - pandoc
  - scipy
  - matplotlib
  - pip:
    - pennylane
    - qiskit
    - qiskit-aer
    - qiskit-ibm-runtime
    - ray
    - pytest
    - sphinx
    - sphinx-rtd-theme
    - nbsphinx
    - sphinxcontrib-bibtex
    - ipykernel